name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

  # Allows for running this workflow manually from the GitHub Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run build
        run: yarn build

      - name: Run tests
        run: yarn test
